-- Deliverable 7
DROP TABLE IF EXISTS DOCTOR_BACKUP;
CREATE TABLE DOCTOR_BACKUP LIKE DOCTOR;
INSERT INTO DOCTOR_BACKUP
SELECT* FROM DOCTOR;

DROP TABLE IF EXISTS PATIENT_BACKUP;
CREATE TABLE PATIENT_BACKUP LIKE PATIENT;
INSERT INTO PATIENT_BACKUP
SELECT* FROM PATIENT;

DROP TABLE IF EXISTS PRESCRIPTION_BACKUP;
CREATE TABLE PRESCRIPTION_BACKUP LIKE PRESCRIPTION;
INSERT INTO PRESCRIPTION_BACKUP
SELECT* FROM PRESCRIPTION;

DROP TABLE IF EXISTS APPOINTMENT_BACKUP;
CREATE TABLE APPOINTMENT_BACKUP LIKE APPOINTMENT;
INSERT INTO APPOINTMENT_BACKUP
SELECT* FROM APPOINTMENT;

DROP TABLE IF EXISTS MEDICAL_TEST_BACKUP;
CREATE TABLE MEDICAL_TEST_BACKUP LIKE MEDICAL_TEST;
INSERT INTO MEDICAL_TEST_BACKUP
SELECT* FROM MEDICAL_TEST;

DROP TABLE IF EXISTS AUDIT_BACKUP;
CREATE TABLE AUDIT_BACKUP LIKE AUDIT;
INSERT INTO AUDIT_BACKUP
SELECT* FROM AUDIT;
